apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jira-hpa-sts
  namespace: jira
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: jira-set
  targetCPUUtilizationPercentage: 20
