apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgress-jira-data
  namespace: jira
  labels:
    app: postgress-jira
    tier: frontend
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  claimRef:
    namespace: jira
    name: postgress-jira-data
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.22.160
    # Exported path of your NFS server
    path: "/nfs/jira/postgress"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pvc-shared
  namespace: jira
  labels:
    app: jira-set
    tier: frontend
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  claimRef:
    namespace: jira
    name: jira-pvc-shared
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.22.160
    # Exported path of your NFS server
    path: "/nfs/jira/data"